name: Inputs, outputs, and variables

on:
  push:


jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a value
        id: generate
        run: |
          RANDOM_STRING=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 12)
          echo "Random string: ${RANDOM_STRING}"
          
          echo "random-string=${RANDOM_STRING}" >> $GITHUB_OUTPUT
          echo "constant=1234" >> $GITHUB_OUTPUT

      - name: Outputs direkt nutzen
        run: |
          echo "Random string: ${{ steps.generate.outputs.random-string }}"
          echo "Constant: ${{ steps.generate.outputs.constant }}"

      - name: Outputs als Umgebungsvariablen nutzen
        env:
          PREFIX: pre
          KEY: ${{ steps.generate.outputs.random-string }}
          ID: ${{ steps.generate.outputs.constant }}
        run: |
          echo "${PREFIX}-${KEY}-${ID}"
